# Datensatz Vorstandsvorsitzende#
Codebuch Stand 2020-07-12  
erstellt von Eva, Lorena, Julika, Cameron

## Inhalt
- Edges.csv (Edgelist)
- Nodes.csv (Nodelist)
- Codebuch.rm (Codierung der Datensätze)

## Ursprung und Datenerhebung

Das Netzwerk ist ein *ungerichtetes two-mode Akteursnetzwerk*. 

# EDGE-Attribute

**id**  
(eindeutige Codierung des Knoten)   

**weight**
1= sehr schwache Beziehung
5= sehr starke Beziehung

**relationship**
Beziehungsart zwischen den Personen/Organisationen  
1 = geschäftlich
2 = privat 

**time**  
1 = 0-3 Jahre
2 = 4-6 Jahre
3 = 7-9 Jahre
4 = über 9 Jahre


# NODE-Attribute  
  
**id**  
Identische ID wie aus der edgelist zur Identifikation der Knoten. In diesem Fall sind alle personenbezogenen Daten anonymisiert von 1 bis 38.

**sex**    
Bitte geben Sie ihr Geschlecht an:  
1 = weiblich  
2 = männlich  
3 = divers  


**age**    
in Jahrgang

**power**  
1 = sehr gering
5 = sehr hoch

**company***    
1 =  Edeka 
2 =  REWE Group
3 =  Schwarz Gruppe
4 =  Metro
5 =  Tengelmann 
  
**type**     
1 = Organisation 
2 = Person
  
**education**  
#höchster Bildungsabschluss     
1 = Wirtschaftswissenschaften   
2 = Naturwissenschaften    
3 = Ingenieurswissenschaften   
4 = Geisteswissenschaften
5 = Sozialwissenschaften     

**internationality**  
#Auslandsaufenthalt

1 =  ja     
2 =  nein  

**nationality**  
#nach Pass

1 =  deutsch    
2 =  französisch 
3 =  itallienisch 
4 =  amerikanisch
5 =  sontige

**status**  


1 =  Eigentümer  
2 =  Aufsichtsrat
3 =  Vorstandsmitglied
4 =  

